# -*- coding: utf-8 -*-
"""Couseforbeginning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7pZt_s4BHvFqggi_9knZHzSR-pEfbeB
"""



2+2

2+2

2 +2
3*3

print (2+2)
print (3*3)

#this is a text

print ("hello world")

!ls

# Commented out IPython magic to ensure Python compatibility.
# %timeit [i**2 for i in range(1000)]

# Commented out IPython magic to ensure Python compatibility.
# %%timeit
# L = []
# for i in range(1000):
#     L.append(i**2)
#

L = []
for i in range(1000):
    L.append(i**2)

    print (L)

salary = 100000

salary

base_salary = 1000
bonus_rate = .10

total_salary = base_salary * (1+bonus_rate)

total_salary

print

type(print)

id(base_salary)

my_print = print

my_print ( 'hello world')

def greet():
  return "whatsup  nerd"

greet()

job_title = 'BP'
job_country = 'Brazil'
job_salary = 90

print(f"job: {job_title}\ location : {job_country} \ salary: {job_salary}")

def display_info(title,country,salary):
  return print(f"job: {title}\ location : {country} \ salary: {salary}")

display_info(job_title,job_country,job_salary)

